services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./ha-config:/config
      - ../custom_components:/config/custom_components
    ports:
      - "8124:8123"
    restart: unless-stopped
